import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const html = readFileSync(path.join(root, 'dist', 'index.html'), 'utf8')
const robots = readFileSync(path.join(root, 'dist', 'robots.txt'), 'utf8')
const vercel = JSON.parse(readFileSync(path.join(root, 'vercel.json'), 'utf8'))
const seoManager = readFileSync(path.join(root, 'src', 'components', 'common', 'SeoManager.jsx'), 'utf8')
const productPage = readFileSync(path.join(root, 'src', 'pages', 'ProductDetailsPage.jsx'), 'utf8')
const categoryPage = readFileSync(path.join(root, 'src', 'pages', 'CategoryDetailsPage.jsx'), 'utf8')
const categoryCard = readFileSync(path.join(root, 'src', 'components', 'home', 'CategoryCard.jsx'), 'utf8')
const sitemapController = readFileSync(path.join(root, '..', 'server', 'controllers', 'seoController.js'), 'utf8')
const appBootstrap = readFileSync(path.join(root, 'src', 'components', 'common', 'AppBootstrap.jsx'), 'utf8')
const visitorTracker = readFileSync(path.join(root, 'src', 'components', 'common', 'VisitorTracker.jsx'), 'utf8')

assert.match(html, /<html lang="en-LK">/)
assert.ok(html.includes('<title>Custom Gifts Batticaloa &amp; Sri Lanka | Eshaz Dream World</title>'))
assert.match(html, /name="description"/)
assert.match(html, /name="keywords" content="[^"]*custom gifts Batticaloa/)
assert.match(html, /name="robots" content="index, follow/)
assert.match(html, /name="google-site-verification" content="jPWEIY76vvhyNphtVBY_g4rh5J0ctrJ9HytwmvmgbnY"/)
assert.match(html, /property="og:title"/)
assert.match(html, /name="twitter:card"/)
const socialImage = html.match(/property="og:image" content="https:\/\/eshazdreamworld\.vercel\.app(\/[^"?]+)"/)?.[1]
assert.ok(socialImage, 'The Open Graph image must use an absolute production URL')
assert.ok(existsSync(path.join(root, 'dist', socialImage)), 'The Open Graph image must exist in the production build')
assert.equal(html.match(/property="og:image:secure_url" content="([^"]+)"/)?.[1], `https://eshazdreamworld.vercel.app${socialImage}`, 'The secure Open Graph image must match the canonical image')
assert.equal(html.match(/property="og:image:type" content="([^"]+)"/)?.[1], 'image/jpeg', 'The Open Graph image must declare its MIME type')
assert.equal(html.match(/name="twitter:image" content="([^"]+)"/)?.[1], `https://eshazdreamworld.vercel.app${socialImage}`, 'Twitter must use the same current social image')
assert.match(socialImage, /2026-07/, 'The social image URL must be versioned so crawlers do not reuse an older cached logo')
const favicon = html.match(/rel="icon"[^>]+href="([^"]+)"/)?.[1]
const appleTouchIcon = html.match(/rel="apple-touch-icon"[^>]+href="([^"]+)"/)?.[1]
assert.ok(favicon && existsSync(path.join(root, 'dist', favicon)), 'The current Google-compatible favicon must exist')
assert.ok(appleTouchIcon && existsSync(path.join(root, 'dist', appleTouchIcon)), 'The current Apple touch icon must exist')
assert.match(html, /id="edw-structured-data"/)
assert.match(html, /eshaz-dream-world-logo-2026-07\.png/)
assert.match(html, /"addressLocality": "Batticaloa"/)
assert.match(html, /"@type": "SearchAction"/)
assert.match(html, /<link rel="canonical" href="https:\/\/eshazdreamworld\.vercel\.app\/"/)
assert.match(robots, /Sitemap: https:\/\/eshazdreamworld\.vercel\.app\/sitemap\.xml/)
assert.match(robots, /Allow: \/api\/storefront\/bootstrap/)
assert.match(robots, /Disallow: \/api\//)
assert.doesNotMatch(robots, /Disallow: \/admin/)
assert.ok(vercel.rewrites.some((rewrite) => rewrite.source === '/sitemap.xml' && rewrite.destination.endsWith('/sitemap.xml')))
assert.ok(vercel.rewrites.some((rewrite) => rewrite.source === '/merchant-feed.xml' && rewrite.destination.endsWith('/merchant-feed.xml')))
assert.ok(vercel.headers.some((rule) => rule.headers?.some((header) => header.key === 'X-Robots-Tag' && header.value === 'noindex, nofollow')))
assert.match(seoManager, /'@type': \['OnlineStore', 'Store'\]/)
assert.match(seoManager, /'@type': 'WebSite'/)
assert.match(seoManager, /addressLocality: 'Batticaloa'/)
assert.match(productPage, /'@type': 'ProductGroup'/)
assert.match(productPage, /'@type': 'Product'/)
assert.match(productPage, /hasVariant/)
assert.match(productPage, /'@type': 'OfferShippingDetails'/)
assert.match(productPage, /'@type': 'BreadcrumbList'/)
assert.match(productPage, /'@type': 'AggregateRating'/)
assert.match(categoryPage, /'@type': 'CollectionPage'/)
assert.match(categoryPage, /'@type': 'ItemList'/)
assert.match(categoryPage, /'@type': 'BreadcrumbList'/)
assert.match(categoryCard, /to=\{`\/category\/\$\{category\.slug\}`\}/)
assert.match(sitemapController, /\/category\/\$\{encodeURIComponent\(category\.slug\)\}/)
assert.match(appBootstrap, /isSearchCrawler\(\)/)
assert.match(visitorTracker, /isAutomatedAnalyticsClient\(\)/)

console.log('SEO smoke test passed: metadata, social image, crawlable storefront data, crawler-safe analytics, canonical URLs, product variants, shipping details, robots, and structured data are configured.')
