import { yupResolver } from '@hookform/resolvers/yup'
import { useForm } from 'react-hook-form'
import { FiLock } from 'react-icons/fi'
import toast from 'react-hot-toast'
import { useDispatch, useSelector } from 'react-redux'
import LoadingButton from '../components/common/LoadingButton.jsx'
import PasswordInput from '../components/common/PasswordInput.jsx'
import { changePassword } from '../redux/slices/authSlice.js'
import { changePasswordSchema } from '../utils/validationSchemas.js'
function ProfileSettingsPage() { const dispatch = useDispatch(); const { user, isLoading, error } = useSelector((state) => state.auth); const { register, reset, handleSubmit, formState: { errors } } = useForm({ resolver: yupResolver(changePasswordSchema) }); const save = async (values) => { try { await dispatch(changePassword(values)).unwrap(); reset(); toast.success('Password changed successfully.') } catch { /* Inline below. */ } }; return <div className="grid gap-6 xl:grid-cols-2"><section className="form-section"><h2 className="form-section-title"><span><FiLock /></span> Change Password</h2>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error.message}</p>}<form onSubmit={handleSubmit(save)} className="mt-6 space-y-4"><PasswordInput label="Current password" autoComplete="current-password" error={errors.currentPassword?.message} {...register('currentPassword')} /><PasswordInput label="New password" autoComplete="new-password" error={errors.newPassword?.message} {...register('newPassword')} /><PasswordInput label="Confirm new password" autoComplete="new-password" error={errors.confirmNewPassword?.message} {...register('confirmNewPassword')} /><LoadingButton loading={isLoading} type="submit" className="primary-button">Update Password</LoadingButton></form></section><section className="space-y-6"><div className="form-section"><h2 className="font-serif text-2xl font-semibold">Account information</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs text-muted">Name</dt><dd>{user.fullName}</dd></div><div><dt className="text-xs text-muted">Email</dt><dd>{user.email}</dd></div><div><dt className="text-xs text-muted">Member since</dt><dd>{new Date(user.createdAt).toLocaleDateString()}</dd></div></dl></div><div className="form-section opacity-75"><h2 className="font-serif text-2xl font-semibold">Advanced account actions</h2><p className="mt-3 text-sm leading-6 text-muted">Logout from all devices and account deletion are unavailable in Phase 3.</p><div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled className="secondary-button">Logout all devices</button><button type="button" disabled className="secondary-button text-red-600">Delete account</button></div></div></section></div> }
export default ProfileSettingsPage
