import { useState } from 'react'
import { FiMapPin, FiPlus } from 'react-icons/fi'
import toast from 'react-hot-toast'
import { useDispatch, useSelector } from 'react-redux'
import AddressCard from '../components/account/AddressCard.jsx'
import AddressFormModal from '../components/account/AddressFormModal.jsx'
import ConfirmModal from '../components/common/ConfirmModal.jsx'
import EmptyState from '../components/common/EmptyState.jsx'
import { addAddress, deleteAddress, setDefaultAddress, updateAddress } from '../redux/slices/authSlice.js'
function ProfileAddressesPage() { const dispatch = useDispatch(); const { user, isLoading, error } = useSelector((state) => state.auth); const [editor, setEditor] = useState({ open: false, address: null }); const [removing, setRemoving] = useState(null); const save = async (values) => { try { if (editor.address) await dispatch(updateAddress({ addressId: editor.address._id || editor.address.id, body: values })).unwrap(); else await dispatch(addAddress(values)).unwrap(); toast.success('Address saved successfully.'); setEditor({ open: false, address: null }) } catch { /* Inline in modal. */ } }; const remove = async () => { try { await dispatch(deleteAddress(removing._id || removing.id)).unwrap(); toast.success('Address removed successfully.'); setRemoving(null) } catch (err) { toast.error(err?.message || 'Unable to remove address.') } }; const makeDefault = async (id) => { try { await dispatch(setDefaultAddress(id)).unwrap(); toast.success('Default address updated.') } catch (err) { toast.error(err?.message || 'Unable to update address.') } }; const addresses = user.addresses || []; return <div className="form-section"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-serif text-3xl font-semibold">My Addresses</h2><p className="mt-1 text-sm text-muted">Save up to five Sri Lankan delivery addresses.</p></div><button type="button" className="primary-button" disabled={addresses.length >= 5} onClick={() => setEditor({ open: true, address: null })}><FiPlus /> Add Address</button></div>{addresses.length >= 5 && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">You have reached the maximum of five saved addresses.</p>}<div className="mt-6 grid gap-4 xl:grid-cols-2">{addresses.map((address) => <AddressCard key={address._id || address.id} address={address} onEdit={(item) => setEditor({ open: true, address: item })} onDelete={setRemoving} onDefault={makeDefault} loading={isLoading} />)}</div>{!addresses.length && <div className="mt-6"><EmptyState icon={<FiMapPin />} title="No saved addresses" message="Add an address to make future deliveries easier." /></div>}<AddressFormModal open={editor.open} address={editor.address} onClose={() => setEditor({ open: false, address: null })} onSubmit={save} loading={isLoading} apiError={error?.message} /><ConfirmModal open={Boolean(removing)} title="Delete this address?" message="This saved delivery address will be permanently removed." confirmLabel="Delete Address" onClose={() => setRemoving(null)} onConfirm={remove} loading={isLoading} /></div> }
export default ProfileAddressesPage
