import { useState } from 'react'
import { FiSearch, FiTruck } from 'react-icons/fi'
import { useForm } from 'react-hook-form'
import LoadingButton from '../components/common/LoadingButton.jsx'
import OrderTimeline from '../components/order/OrderTimeline.jsx'
import PageTransition from '../components/common/PageTransition.jsx'
import { checkoutApi } from '../services/checkoutApi.js'
import { EMAIL_ERROR, emailPattern, normalizeEmailInput } from '../utils/inputValidation.js'

function TrackOrderPage() {
  const { register, handleSubmit, formState: { errors } } = useForm(), [order, setOrder] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(false)
  const track = async (values) => { setLoading(true); setError(''); try { setOrder(await checkoutApi.trackOrder(values)) } catch (requestError) { setOrder(null); setError(requestError.response?.data?.message || 'Unable to find that order.') } finally { setLoading(false) } }
  return <PageTransition><section className="bg-pink-light/25 py-12"><div className="section-shell"><div className="mx-auto max-w-3xl"><div className="text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-white text-2xl text-rosewood shadow-luxury"><FiTruck /></span><h1 className="mt-5 font-serif text-5xl font-semibold">Track Your Order</h1><p className="mt-3 text-sm text-muted">Enter the order number and checkout email exactly as shown on your confirmation.</p></div><form onSubmit={handleSubmit(track)} className="mt-8 grid gap-4 rounded-[2rem] border border-gold/20 bg-white p-6 shadow-luxury sm:grid-cols-2 sm:p-8" noValidate><label><span className="form-label">Order number</span><input className="input-field uppercase" maxLength={15} placeholder="EDW-2026-000001" {...register('orderNumber', { required: 'Order number is required.', pattern: { value: /^EDW-\d{4}-\d{6}$/i, message: 'Enter a valid EDW order number.' } })} />{errors.orderNumber && <p className="mt-1 text-xs text-red-600">{errors.orderNumber.message}</p>}</label><label><span className="form-label">Email address</span><input className="input-field" type="email" inputMode="email" autoComplete="email" maxLength={160} {...register('email', { required: 'Email is required.', setValueAs: normalizeEmailInput, pattern: { value: emailPattern, message: EMAIL_ERROR } })} />{errors.email && <p className="mt-1 text-xs text-red-600">{errors.email.message}</p>}</label><LoadingButton type="submit" loading={loading} className="primary-button sm:col-span-2"><FiSearch /> Track Order</LoadingButton>{error && <p className="rounded-xl bg-red-50 p-3 text-center text-sm text-red-700 sm:col-span-2">{error}</p>}</form>{order && <section className="mt-7 grid gap-6 rounded-[2rem] border border-gold/20 bg-white p-7 shadow-luxury sm:grid-cols-[1fr_1.2fr]"><div><p className="text-xs uppercase tracking-wider text-gold">{order.orderNumber}</p><h2 className="mt-2 font-serif text-3xl font-semibold">{order.orderStatus}</h2><dl className="mt-5 space-y-3 text-sm"><div><dt className="text-xs text-muted">Tracking number</dt><dd className="font-semibold">{order.trackingNumber || 'Assigned after dispatch'}</dd></div><div><dt className="text-xs text-muted">Estimated delivery</dt><dd className="font-semibold">{order.estimatedDelivery ? new Date(order.estimatedDelivery).toLocaleDateString() : 'To be confirmed'}</dd></div><div><dt className="text-xs text-muted">Payment status</dt><dd className="font-semibold">{order.paymentStatus}</dd></div></dl></div><OrderTimeline timeline={order.timeline} status={order.orderStatus} /></section>}</div></div></section></PageTransition>
}
export default TrackOrderPage
