import { AnimatePresence, motion } from 'framer-motion'
import { useEffect } from 'react'
import { FiAlertTriangle, FiX } from 'react-icons/fi'
function ConfirmModal({ open, title, message, confirmLabel = 'Confirm', onConfirm, onClose, loading = false }) {
  useEffect(() => { if (!open) return undefined; const key = (event) => event.key === 'Escape' && onClose(); document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key) }, [open, onClose])
  return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-[90] grid place-items-center bg-ink/30 p-3 backdrop-blur-sm sm:p-5" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(event) => event.target === event.currentTarget && onClose()}><motion.div role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" className="w-full max-w-md rounded-[1.5rem] bg-white p-5 shadow-2xl sm:rounded-[1.75rem] sm:p-8" initial={{ scale: .96, y: 10 }} animate={{ scale: 1, y: 0 }} exit={{ scale: .96, y: 10 }}><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-pink-light text-rosewood"><FiAlertTriangle /></span><button type="button" className="icon-button" onClick={onClose} aria-label="Close confirmation"><FiX /></button></div><h2 id="confirm-title" className="mt-5 break-words font-serif text-2xl font-semibold">{title}</h2><p className="mt-2 break-words text-sm leading-6 text-muted">{message}</p><div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" className="secondary-button w-full sm:w-auto" onClick={onClose} disabled={loading}>Cancel</button><LoadingButton loading={loading} className="primary-button w-full sm:w-auto" onClick={onConfirm}>{confirmLabel}</LoadingButton></div></motion.div></motion.div>}</AnimatePresence>
}
import LoadingButton from './LoadingButton.jsx'
export default ConfirmModal
