import { useCallback, useState } from 'react'
import { FiEye } from 'react-icons/fi'
import { Link } from 'react-router-dom'
import AdminPageHeader from '../../components/admin/AdminPageHeader.jsx'
import AdminPagination from '../../components/admin/AdminPagination.jsx'
import DataTable from '../../components/admin/DataTable.jsx'
import StatusBadge from '../../components/admin/StatusBadge.jsx'
import { useAdminQuery } from '../../hooks/useAdminQuery.js'
import { adminApi } from '../../services/adminApi.js'
import { formatCurrency } from '../../utils/formatCurrency.js'
const statuses = ['', 'Pending', 'Confirmed', 'Processing', 'Packed', 'Shipped', 'Delivered', 'Cancelled']
function AdminOrdersPage() { const [query, setQuery] = useState({ page: 1, search: '', status: '', payment: '' }); const fetcher = useCallback(() => adminApi.list('orders', query), [query]); const { data, loading, error } = useAdminQuery(fetcher, [fetcher]); const columns = [{ key: 'number', label: 'Order', render: (row) => <div><strong>{row.orderNumber}</strong><p className="text-xs text-muted">{new Date(row.createdAt).toLocaleDateString()}</p></div> }, { key: 'customer', label: 'Customer', render: (row) => row.user ? <div><p>{row.user.firstName} {row.user.lastName}</p><p className="text-xs text-muted">{row.user.email}</p></div> : 'Deleted user' }, { key: 'items', label: 'Items', render: (row) => row.items.reduce((sum, item) => sum + item.quantity, 0) }, { key: 'total', label: 'Total', render: (row) => formatCurrency(row.total) }, { key: 'payment', label: 'Payment', render: (row) => <StatusBadge>{row.paymentStatus}</StatusBadge> }, { key: 'status', label: 'Order status', render: (row) => <StatusBadge>{row.orderStatus}</StatusBadge> }, { key: 'view', label: '', render: (row) => <Link to={`/admin/orders/${row.id}`} className="icon-button" aria-label="View order"><FiEye /></Link> }]; return <div className="space-y-6"><AdminPageHeader title="Orders" description="Review customer orders and manage fulfillment, tracking, and payment status." /><div className="overflow-hidden rounded-[1.75rem] border border-gold/15 bg-white"><div className="grid gap-3 p-4 sm:grid-cols-3"><input className="input-field" placeholder="Search order number…" value={query.search} onChange={(e) => setQuery((current) => ({ ...current, search: e.target.value, page: 1 }))} /><select className="input-field" value={query.status} onChange={(e) => setQuery((current) => ({ ...current, status: e.target.value, page: 1 }))}>{statuses.map((status) => <option key={status || 'all'} value={status}>{status || 'All order statuses'}</option>)}</select><select className="input-field" value={query.payment} onChange={(e) => setQuery((current) => ({ ...current, payment: e.target.value, page: 1 }))}><option value="">All payment statuses</option><option>Pending</option><option>Paid</option><option>Failed</option><option>Refunded</option></select></div>{error ? <p className="p-5 text-red-600">{error}</p> : <DataTable columns={columns} rows={data?.orders} loading={loading} emptyTitle="No orders found" />}<AdminPagination pagination={data?.pagination} onPage={(page) => setQuery((current) => ({ ...current, page }))} /></div></div> }
export default AdminOrdersPage
