const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character])
const money = (value) => new Intl.NumberFormat('en-LK', { style: 'currency', currency: 'LKR' }).format(value)

const layout = (title, content, action) => `<!doctype html><html><head><meta name="viewport" content="width=device-width"><meta charset="utf-8"></head><body style="margin:0;background:#fff8fa;font-family:Arial,sans-serif;color:#34252b"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:32px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;margin:auto;background:#fff;border:1px solid #ecd9d4;border-radius:24px;overflow:hidden"><tr><td style="padding:30px;text-align:center;background:linear-gradient(135deg,#fff2f7,#fffaf1)"><div style="font-family:Georgia,serif;font-size:30px;color:#7d2948">Eshaz Dream World</div><div style="font-size:12px;letter-spacing:2px;color:#b38a45;margin-top:8px">YOUR DESTINATION | MY PASSION</div></td></tr><tr><td style="padding:32px"><h1 style="font:28px Georgia,serif;margin:0 0 18px">${escapeHtml(title)}</h1>${content}${action ? `<p style="margin:28px 0 0"><a href="${escapeHtml(action.url)}" style="display:inline-block;padding:13px 22px;border-radius:999px;background:#8c3153;color:white;text-decoration:none;font-weight:bold">${escapeHtml(action.label)}</a></p>` : ''}</td></tr><tr><td style="padding:22px 32px;background:#34252b;color:#f8e8ee;font-size:12px;text-align:center">Handcrafted with care by Eshaz Dream World</td></tr></table></td></tr></table></body></html>`
const paragraph = (text) => `<p style="font-size:15px;line-height:1.7;color:#6f5b63">${escapeHtml(text)}</p>`

export const welcomeEmail = (user, clientUrl) => ({ subject: 'Welcome to Eshaz Dream World', html: layout(`Welcome, ${user.firstName}!`, paragraph('Your account is ready. Discover thoughtful creations made to turn your ideas into something beautiful.'), { label: 'Explore Collections', url: `${clientUrl}/shop` }) })
export const passwordResetEmail = (user, resetUrl) => ({ subject: 'Reset your Eshaz Dream World password', html: layout('Reset your password', `${paragraph(`Hello ${user.firstName}, use the secure button below to choose a new password.`)}${paragraph('This link expires in 30 minutes. If you did not request it, you can safely ignore this email.')}`, { label: 'Reset Password', url: resetUrl }) })
export const orderConfirmationEmail = (user, order, clientUrl) => ({ subject: `Order ${order.orderNumber} confirmed`, html: layout('Thank you for your order', `${paragraph(`Hello ${user.firstName}, we received order ${order.orderNumber}.`)}${paragraph(`Total: ${money(order.total)} · Payment: ${order.paymentMethod === 'COD' ? 'Cash on Delivery' : order.paymentStatus}`)}`, { label: 'View Order', url: `${clientUrl}/orders/${order.orderNumber}` }) })
export const paymentSuccessEmail = (user, order, clientUrl) => ({ subject: `Payment received for ${order.orderNumber}`, html: layout('Payment successful', `${paragraph(`We securely received ${money(order.total)} for order ${order.orderNumber}.`)}${paragraph('Your creation will now move into preparation.')}`, { label: 'View Order', url: `${clientUrl}/orders/${order.orderNumber}` }) })
export const paymentFailedEmail = (user, clientUrl) => ({ subject: 'Your Eshaz Dream World payment needs attention', html: layout('Payment was not completed', paragraph('Your card was not charged successfully. Your cart is still available, so you can safely try again.'), { label: 'Return to Checkout', url: `${clientUrl}/checkout` }) })
export const orderStatusEmail = (user, order, clientUrl) => ({ subject: `Order ${order.orderNumber} is ${order.orderStatus.toLowerCase()}`, html: layout(`Order ${order.orderStatus}`, `${paragraph(`Hello ${user.firstName}, your order ${order.orderNumber} is now ${order.orderStatus.toLowerCase()}.`)}${order.trackingNumber ? paragraph(`Tracking number: ${order.trackingNumber}`) : ''}`, { label: 'Track Order', url: `${clientUrl}/orders/${order.orderNumber}` }) })
export const notificationEmail = (user, title, message, url) => ({ subject: title, html: layout(title, `${paragraph(`Hello ${user.firstName},`)}${paragraph(message)}`, { label: 'View Update', url }) })
