import Banner from '../models/Banner.js'
import { paginationData, paginationFromQuery } from '../utils/queryUtils.js'
import { AppError, sendSuccess } from '../utils/responseUtils.js'
import { deleteImage } from '../utils/cloudinaryUtils.js'

export async function listActiveBanners(_request, response) { const now = new Date(); const banners = await Banner.find({ isActive: true, $and: [{ $or: [{ startsAt: null }, { startsAt: { $lte: now } }] }, { $or: [{ endsAt: null }, { endsAt: { $gte: now } }] }] }).sort({ sortOrder: 1, createdAt: -1 }); return sendSuccess(response, { message: 'Banners retrieved', data: { banners } }) }
export async function listBanners(request, response) { const { page, limit, skip } = paginationFromQuery(request.query, { defaultLimit: 10 }); const filter = {}; if (request.query.status === 'active') filter.isActive = true; if (request.query.status === 'inactive') filter.isActive = false; if (request.query.position) filter.position = request.query.position; const [banners, total] = await Promise.all([Banner.find(filter).sort({ sortOrder: 1, createdAt: -1 }).skip(skip).limit(limit), Banner.countDocuments(filter)]); return sendSuccess(response, { message: 'Admin banners retrieved', data: { banners, pagination: paginationData(total, page, limit) } }) }
export async function createBanner(request, response) { const banner = await Banner.create(request.validatedBody); return sendSuccess(response, { statusCode: 201, message: 'Banner created successfully', data: { banner } }) }
export async function updateBanner(request, response) { const banner = await Banner.findById(request.params.id); if (!banner) throw new AppError('Banner not found', 404); const previousImage = banner.image?.publicId; Object.assign(banner, request.validatedBody); await banner.save(); if (previousImage && previousImage !== banner.image?.publicId) await deleteImage(previousImage).catch(() => {}); return sendSuccess(response, { message: 'Banner updated successfully', data: { banner } }) }
export async function deleteBanner(request, response) { const banner = await Banner.findByIdAndDelete(request.params.id); if (!banner) throw new AppError('Banner not found', 404); if (banner.image?.publicId) await deleteImage(banner.image.publicId).catch(() => {}); return sendSuccess(response, { message: 'Banner deleted successfully' }) }
export async function toggleBanner(request, response) { const banner = await Banner.findById(request.params.id); if (!banner) throw new AppError('Banner not found', 404); banner.isActive = !banner.isActive; await banner.save(); return sendSuccess(response, { message: 'Banner status updated', data: { banner } }) }
