import Category from '../models/Category.js'
import Product from '../models/Product.js'
import { escapeRegex, paginationData, paginationFromQuery } from '../utils/queryUtils.js'
import { AppError, sendSuccess } from '../utils/responseUtils.js'
import { deleteImage } from '../utils/cloudinaryUtils.js'

export async function listCategories(_request, response) { const categories = await Category.find({ isActive: true }).populate('parentCategory', 'name slug').sort({ sortOrder: 1, name: 1 }).lean(); const counts = await Product.aggregate([{ $group: { _id: '$category', count: { $sum: 1 } } }]); const countMap = new Map(counts.map((entry) => [String(entry._id), entry.count])); return sendSuccess(response, { message: 'Categories retrieved', data: { categories: categories.map((category) => ({ ...category, id: String(category._id), productCount: countMap.get(String(category._id)) || 0 })) } }) }
export async function adminListCategories(request, response) { const { page, limit, skip } = paginationFromQuery(request.query, { defaultLimit: 20 }); const filter = {}; if (request.query.search) { const pattern = new RegExp(escapeRegex(String(request.query.search).slice(0, 100)), 'i'); filter.$or = [{ name: pattern }, { slug: pattern }] } if (request.query.status === 'active') filter.isActive = true; if (request.query.status === 'inactive') filter.isActive = false; const [categories, total] = await Promise.all([Category.find(filter).populate('parentCategory', 'name slug').sort({ sortOrder: 1, name: 1 }).skip(skip).limit(limit), Category.countDocuments(filter)]); return sendSuccess(response, { message: 'Admin categories retrieved', data: { categories, pagination: paginationData(total, page, limit) } }) }
export async function createCategory(request, response) { if (request.validatedBody.parentCategory && String(request.validatedBody.parentCategory) === String(request.params.id)) throw new AppError('A category cannot be its own parent', 422); const category = await Category.create(request.validatedBody); return sendSuccess(response, { statusCode: 201, message: 'Category created successfully', data: { category } }) }
export async function updateCategory(request, response) { const category = await Category.findById(request.params.id); if (!category) throw new AppError('Category not found', 404); if (request.validatedBody.parentCategory === String(category._id)) throw new AppError('A category cannot be its own parent', 422); const previousImage = category.image?.publicId; Object.assign(category, request.validatedBody); await category.save(); if (previousImage && previousImage !== category.image?.publicId) await deleteImage(previousImage).catch(() => {}); return sendSuccess(response, { message: 'Category updated successfully', data: { category } }) }
export async function deleteCategory(request, response) { const [category, productCount, childCount] = await Promise.all([Category.findById(request.params.id), Product.countDocuments({ category: request.params.id }), Category.countDocuments({ parentCategory: request.params.id })]); if (!category) throw new AppError('Category not found', 404); if (productCount || childCount) throw new AppError('Category cannot be deleted while it has products or child categories', 409); await category.deleteOne(); if (category.image?.publicId) await deleteImage(category.image.publicId).catch(() => {}); return sendSuccess(response, { message: 'Category deleted successfully' }) }
