import Coupon from '../models/Coupon.js'
import { escapeRegex, paginationData, paginationFromQuery } from '../utils/queryUtils.js'
import { AppError, sendSuccess } from '../utils/responseUtils.js'

export async function listCoupons(request, response) { const { page, limit, skip } = paginationFromQuery(request.query, { defaultLimit: 10 }); const filter = {}; if (request.query.search) filter.code = new RegExp(escapeRegex(request.query.search), 'i'); if (request.query.status === 'active') filter.isActive = true; if (request.query.status === 'inactive') filter.isActive = false; if (request.query.status === 'expired') filter.expiryDate = { $lt: new Date() }; const [coupons, total] = await Promise.all([Coupon.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit), Coupon.countDocuments(filter)]); return sendSuccess(response, { message: 'Coupons retrieved', data: { coupons, pagination: paginationData(total, page, limit) } }) }
export async function createCoupon(request, response) { const coupon = await Coupon.create(request.validatedBody); return sendSuccess(response, { statusCode: 201, message: 'Coupon created successfully', data: { coupon } }) }
export async function updateCoupon(request, response) { const coupon = await Coupon.findById(request.params.id); if (!coupon) throw new AppError('Coupon not found', 404); const usedCount = coupon.usedCount; Object.assign(coupon, request.validatedBody); coupon.usedCount = usedCount; await coupon.save(); return sendSuccess(response, { message: 'Coupon updated successfully', data: { coupon } }) }
export async function deleteCoupon(request, response) { const coupon = await Coupon.findByIdAndDelete(request.params.id); if (!coupon) throw new AppError('Coupon not found', 404); return sendSuccess(response, { message: 'Coupon deleted successfully' }) }
export async function toggleCoupon(request, response) { const coupon = await Coupon.findById(request.params.id); if (!coupon) throw new AppError('Coupon not found', 404); coupon.isActive = !coupon.isActive; await coupon.save(); return sendSuccess(response, { message: 'Coupon status updated', data: { coupon } }) }
