import Product from '../models/Product.js'
import Review from '../models/Review.js'
import { paginationData, paginationFromQuery } from '../utils/queryUtils.js'
import { recalculateProductRating } from '../utils/reviewUtils.js'
import { AppError, sendSuccess } from '../utils/responseUtils.js'

export async function createReview(request, response) { const product = await Product.findById(request.validatedBody.product); if (!product) throw new AppError('Product not found', 404); const review = await Review.create({ ...request.validatedBody, user: request.user._id }); await recalculateProductRating(product._id); await review.populate('user', 'firstName lastName avatar'); return sendSuccess(response, { statusCode: 201, message: 'Review submitted successfully', data: { review } }) }
export async function updateOwnReview(request, response) { const review = await Review.findOne({ _id: request.params.id, user: request.user._id }); if (!review) throw new AppError('Review not found', 404); review.rating = request.validatedBody.rating; review.title = request.validatedBody.title; review.comment = request.validatedBody.comment; await review.save(); await recalculateProductRating(review.product); return sendSuccess(response, { message: 'Review updated successfully', data: { review } }) }
export async function deleteOwnReview(request, response) { const review = await Review.findOne({ _id: request.params.id, user: request.user._id }); if (!review) throw new AppError('Review not found', 404); const productId = review.product; await review.deleteOne(); await recalculateProductRating(productId); return sendSuccess(response, { message: 'Review deleted successfully' }) }
export async function adminListReviews(request, response) { const { page, limit, skip } = paginationFromQuery(request.query, { defaultLimit: 10 }); const filter = {}; if (request.query.status === 'approved') filter.isApproved = true; if (request.query.status === 'pending') filter.isApproved = false; if (request.query.status === 'hidden') filter.isVisible = false; const [reviews, total] = await Promise.all([Review.find(filter).populate('user', 'firstName lastName email').populate('product', 'name slug image').sort({ createdAt: -1 }).skip(skip).limit(limit), Review.countDocuments(filter)]); return sendSuccess(response, { message: 'Reviews retrieved', data: { reviews, pagination: paginationData(total, page, limit) } }) }
export async function moderateReview(request, response) { const review = await Review.findById(request.params.id); if (!review) throw new AppError('Review not found', 404); Object.assign(review, request.validatedBody); await review.save(); await recalculateProductRating(review.product); return sendSuccess(response, { message: 'Review moderation updated', data: { review } }) }
export async function adminDeleteReview(request, response) { const review = await Review.findById(request.params.id); if (!review) throw new AppError('Review not found', 404); const productId = review.product; await review.deleteOne(); await recalculateProductRating(productId); return sendSuccess(response, { message: 'Review deleted successfully' }) }
